### ISSUE TITLE
Flexible-Info-Card centering issue!

### ISSUE THREAD

**Issue by loua0013** [loua0013/flexible-info-card#1]
Hi @mackenzierose 

I am having trouble centering the whole section! Do you see what I'm doing wrong? 
Thank yewww!!

**Comment by MacKenzieRose** [comment]
Hey @loua0013 

If you put a margin of 0 on your `<ul>` it should start keeping everything more in the center.

Let me know if that helps 😸

**Comment by loua0013** [comment]
Thank you!!! It worked!
